breakerbox:
  build: ../
  env_file:
    - ./development.env
  environment:
    - VAULT_ADDR=http://vault:8222
  ports:
    - "8080:8080" # dw application
    - "8081:8081" # dw admin application
  volumes:
    - ./vault-token:/home/app-user/.vault-token
    - ./vault:/usr/bin/vault
    - ./development-secrets.json:/home/app-user/.development-secrets.json
    - ./logs:/home/app-user/logs
  links:
    - "vault"

# vault development support
vault:
  image: sjourdan/vault:latest
  ports:
    - "0.0.0.0:8200:8222" # public API access to typical 8200 via 0.0.0.0:8222 binding
  expose:
    - "8222"
  volumes:
    - ./vault-token:/root/.vault-token
    - ./development-vault.conf:/root/vault.conf
  command: "server -dev -config /root/vault.conf"
